-- =====================================================================
-- V1__init_schema.sql
-- Explicit, versioned schema for TransitOps, generated to match the
-- current JPA entities exactly (com.transitops.entity.*) for PostgreSQL.
-- =====================================================================

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    role            VARCHAR(50)  NOT NULL,
    refresh_token   VARCHAR(500),
    mfa_enabled     BOOLEAN      NOT NULL DEFAULT FALSE,
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP     NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS vehicles (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number    VARCHAR(50)  NOT NULL,
    name                   VARCHAR(255) NOT NULL,
    model                  VARCHAR(255),
    type                   VARCHAR(50),
    max_load_capacity      DOUBLE PRECISION NOT NULL,
    odometer               DOUBLE PRECISION NOT NULL DEFAULT 0,
    acquisition_cost       DECIMAL(14,2),
    qr_code                VARCHAR(255),
    status                 VARCHAR(50)  NOT NULL DEFAULT 'AVAILABLE',
    region                 VARCHAR(255),
    created_at             TIMESTAMP     NOT NULL,
    updated_at             TIMESTAMP     NOT NULL,
    CONSTRAINT uq_vehicles_registration_number UNIQUE (registration_number),
    CONSTRAINT uq_vehicles_qr_code UNIQUE (qr_code)
);

CREATE INDEX IF NOT EXISTS idx_vehicles_status ON vehicles (status);

CREATE TABLE IF NOT EXISTS drivers (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(255) NOT NULL,
    license_number        VARCHAR(50)  NOT NULL,
    license_category      VARCHAR(50),
    license_expiry_date   DATE         NOT NULL,
    contact_number        VARCHAR(50),
    safety_score          INT          NOT NULL DEFAULT 100,
    status                VARCHAR(50)  NOT NULL DEFAULT 'AVAILABLE',
    created_at            TIMESTAMP     NOT NULL,
    updated_at            TIMESTAMP     NOT NULL,
    CONSTRAINT uq_drivers_license_number UNIQUE (license_number)
);

CREATE INDEX IF NOT EXISTS idx_drivers_status ON drivers (status);
CREATE INDEX IF NOT EXISTS idx_drivers_license_expiry_date ON drivers (license_expiry_date);

CREATE TABLE IF NOT EXISTS trips (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_number              VARCHAR(50)  NOT NULL,
    source                   VARCHAR(255) NOT NULL,
    destination              VARCHAR(255) NOT NULL,
    cargo_weight             DOUBLE PRECISION NOT NULL,
    planned_distance         DOUBLE PRECISION,
    final_odometer           DOUBLE PRECISION,
    fuel_consumed            DOUBLE PRECISION,
    expected_fuel_consumed   DOUBLE PRECISION,
    fuel_deviation_percent   DOUBLE PRECISION,
    fuel_theft_suspected     BOOLEAN      NOT NULL DEFAULT FALSE,
    revenue                  DECIMAL(14,2),
    status                   VARCHAR(50)  NOT NULL DEFAULT 'DRAFT',
    vehicle_id               BIGINT       NOT NULL,
    driver_id                BIGINT       NOT NULL,
    dispatched_at            TIMESTAMP,
    completed_at             TIMESTAMP,
    created_at               TIMESTAMP     NOT NULL,
    CONSTRAINT uq_trips_trip_number UNIQUE (trip_number),
    CONSTRAINT fk_trips_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id),
    CONSTRAINT fk_trips_driver FOREIGN KEY (driver_id) REFERENCES drivers (id)
);

CREATE INDEX IF NOT EXISTS idx_trips_status ON trips (status);
CREATE INDEX IF NOT EXISTS idx_trips_vehicle_id ON trips (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_trips_driver_id ON trips (driver_id);
CREATE INDEX IF NOT EXISTS idx_trips_fuel_theft_suspected ON trips (fuel_theft_suspected);

CREATE TABLE IF NOT EXISTS maintenance_logs (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id         BIGINT       NOT NULL,
    description        VARCHAR(500) NOT NULL,
    cost               DECIMAL(14,2),
    maintenance_date   DATE,
    is_active          BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_maintenance_logs_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
);

CREATE INDEX IF NOT EXISTS idx_maintenance_logs_vehicle_id ON maintenance_logs (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_logs_vehicle_active ON maintenance_logs (vehicle_id, is_active);

CREATE TABLE IF NOT EXISTS expenses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id      BIGINT,
    vehicle_id   BIGINT       NOT NULL,
    type         VARCHAR(50)  NOT NULL,
    liters       DOUBLE PRECISION,
    cost         DECIMAL(14,2) NOT NULL,
    date         DATE,
    created_at   TIMESTAMP     NOT NULL,
    CONSTRAINT fk_expenses_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_expenses_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
);

CREATE INDEX IF NOT EXISTS idx_expenses_trip_id ON expenses (trip_id);
CREATE INDEX IF NOT EXISTS idx_expenses_vehicle_id ON expenses (vehicle_id);

CREATE TABLE IF NOT EXISTS audit_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT,
    action        VARCHAR(100) NOT NULL,
    entity_name   VARCHAR(100),
    entity_id     VARCHAR(100),
    old_value     TEXT,
    new_value     TEXT,
    ip_address    VARCHAR(64),
    created_at    TIMESTAMP     NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs (entity_name, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs (created_at);
