-- Alter existing tables to add tenant_id and updated_at where missing
ALTER TABLE users ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(100) NOT NULL DEFAULT 'public';
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(100) NOT NULL DEFAULT 'public';
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(100) NOT NULL DEFAULT 'public';
ALTER TABLE trips ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(100) NOT NULL DEFAULT 'public';
ALTER TABLE trips ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE maintenance_logs ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(100) NOT NULL DEFAULT 'public';
ALTER TABLE maintenance_logs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE maintenance_logs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(100) NOT NULL DEFAULT 'public';
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(100) NOT NULL DEFAULT 'public';
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Create tenants table
CREATE TABLE IF NOT EXISTS tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    subdomain VARCHAR(255),
    configs TEXT,
    status VARCHAR(50),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create organizations
CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    region VARCHAR(255),
    address VARCHAR(255),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create departments
CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    code VARCHAR(100),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create roles
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create permissions
CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100),
    description VARCHAR(255),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create permission groups
CREATE TABLE IF NOT EXISTS permission_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create permission group mappings
CREATE TABLE IF NOT EXISTS permission_group_mappings (
    group_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (group_id, permission_id),
    FOREIGN KEY (group_id) REFERENCES permission_groups(id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

-- Create refresh tokens
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(500),
    expiry_date TIMESTAMP,
    is_revoked BOOLEAN,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create user sessions
CREATE TABLE IF NOT EXISTS user_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address VARCHAR(100),
    user_agent VARCHAR(255),
    device_token VARCHAR(255),
    last_active TIMESTAMP,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create vehicle documents
CREATE TABLE IF NOT EXISTS vehicle_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT,
    document_type VARCHAR(100),
    file_url VARCHAR(500),
    expiry_date DATE,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create vehicle health scores
CREATE TABLE IF NOT EXISTS vehicle_health_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT,
    overall_score DOUBLE PRECISION,
    engine_score DOUBLE PRECISION,
    tyre_score DOUBLE PRECISION,
    battery_score DOUBLE PRECISION,
    brake_score DOUBLE PRECISION,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create vehicle sensors
CREATE TABLE IF NOT EXISTS vehicle_sensors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT,
    sensor_type VARCHAR(100),
    serial_number VARCHAR(100),
    "last_value" DOUBLE PRECISION,
    status VARCHAR(50),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create vehicle insurance
CREATE TABLE IF NOT EXISTS vehicle_insurance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT,
    policy_number VARCHAR(100),
    provider VARCHAR(255),
    cost DECIMAL(14,2),
    start_date DATE,
    end_date DATE,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create maintenance schedules
CREATE TABLE IF NOT EXISTS maintenance_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT,
    service_type VARCHAR(255),
    mileage_interval DOUBLE PRECISION,
    time_interval_days INT,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create maintenance checklists
CREATE TABLE IF NOT EXISTS maintenance_checklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maintenance_log_id BIGINT,
    task_description VARCHAR(500),
    is_required BOOLEAN,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create maintenance history
CREATE TABLE IF NOT EXISTS maintenance_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT,
    part_replaced VARCHAR(255),
    mechanic_name VARCHAR(255),
    duration_hours DOUBLE PRECISION,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create vehicle loans
CREATE TABLE IF NOT EXISTS vehicle_loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT,
    bank_name VARCHAR(255),
    emi_amount DECIMAL(14,2),
    total_paid DECIMAL(14,2),
    remaining_balance DECIMAL(14,2),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create driver documents
CREATE TABLE IF NOT EXISTS driver_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT,
    file_url VARCHAR(500),
    expiry_date DATE,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create driver attendance
CREATE TABLE IF NOT EXISTS driver_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT,
    date DATE,
    check_in TIME,
    check_out TIME,
    gps_lat DOUBLE PRECISION,
    gps_lng DOUBLE PRECISION,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create driver leave requests
CREATE TABLE IF NOT EXISTS driver_leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT,
    start_date DATE,
    end_date DATE,
    leave_type VARCHAR(100),
    status VARCHAR(50),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create driver training
CREATE TABLE IF NOT EXISTS driver_training (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT,
    course_name VARCHAR(255),
    completion_date DATE,
    expiry_date DATE,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create driver violations
CREATE TABLE IF NOT EXISTS driver_violations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT,
    violation_type VARCHAR(255),
    fine_amount DECIMAL(14,2),
    date DATE,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create driver performance
CREATE TABLE IF NOT EXISTS driver_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT,
    harsh_brakes INT,
    over_speed_count INT,
    idle_time_seconds BIGINT,
    night_drive_hours DOUBLE PRECISION,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create driver shifts
CREATE TABLE IF NOT EXISTS driver_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT,
    shift_start TIME,
    shift_end TIME,
    days_of_week VARCHAR(255),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create trip stops
CREATE TABLE IF NOT EXISTS trip_stops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT,
    stop_order INT,
    location_name VARCHAR(255),
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    type VARCHAR(50),
    status VARCHAR(50),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create trip timeline
CREATE TABLE IF NOT EXISTS trip_timeline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT,
    previous_status VARCHAR(50),
    new_status VARCHAR(50),
    timestamp TIMESTAMP,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create trip attachments
CREATE TABLE IF NOT EXISTS trip_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT,
    file_url VARCHAR(500),
    uploaded_at TIMESTAMP,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create trip proofs
CREATE TABLE IF NOT EXISTS trip_proofs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT,
    photo_url VARCHAR(500),
    signature_url VARCHAR(500),
    verification_otp VARCHAR(20),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create route plans
CREATE TABLE IF NOT EXISTS route_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT,
    planned_polyline TEXT,
    estimated_fuel DOUBLE PRECISION,
    toll_cost DECIMAL(14,2),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create geofences
CREATE TABLE IF NOT EXISTS geofences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    center_lat DOUBLE PRECISION,
    center_lng DOUBLE PRECISION,
    radius_meters DOUBLE PRECISION,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create geofence events
CREATE TABLE IF NOT EXISTS geofence_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    geofence_id BIGINT,
    vehicle_id BIGINT,
    entered_at TIMESTAMP,
    exited_at TIMESTAMP,
    event_trigger_type VARCHAR(50),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create cargo items
CREATE TABLE IF NOT EXISTS cargo_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    weight DOUBLE PRECISION,
    volume DOUBLE PRECISION,
    is_fragile BOOLEAN,
    is_dangerous BOOLEAN,
    temperature_range VARCHAR(100),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create warehouses
CREATE TABLE IF NOT EXISTS warehouses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    address VARCHAR(255),
    total_capacity DOUBLE PRECISION,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create docks
CREATE TABLE IF NOT EXISTS docks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT,
    dock_number VARCHAR(50),
    is_occupied BOOLEAN,
    occupied_until TIMESTAMP,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create inventory batches
CREATE TABLE IF NOT EXISTS inventory_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT,
    cargo_item_id BIGINT,
    quantity INT,
    storage_bay VARCHAR(100),
    last_audited DATE,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create stock transfers
CREATE TABLE IF NOT EXISTS stock_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_warehouse_id BIGINT,
    dest_warehouse_id BIGINT,
    cargo_item_id BIGINT,
    quantity INT,
    status VARCHAR(50),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create dock queues
CREATE TABLE IF NOT EXISTS dock_queues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dock_id BIGINT,
    vehicle_id BIGINT,
    priority INT,
    scheduled_time TIMESTAMP,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create cargo manifests
CREATE TABLE IF NOT EXISTS cargo_manifests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifest_number VARCHAR(100),
    declared_value DECIMAL(14,2),
    carrier_name VARCHAR(255),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create fuel logs
CREATE TABLE IF NOT EXISTS fuel_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT,
    fuel_station VARCHAR(255),
    liters DOUBLE PRECISION,
    cost_per_liter DECIMAL(14,2),
    total_cost DECIMAL(14,2),
    odometer_reading DOUBLE PRECISION,
    is_theft_suspected BOOLEAN,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create fuel cards
CREATE TABLE IF NOT EXISTS fuel_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_number VARCHAR(100),
    provider VARCHAR(255),
    expiry DATE,
    limit_amount DECIMAL(14,2),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create invoices
CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT,
    client_name VARCHAR(255),
    amount DECIMAL(14,2),
    tax DECIMAL(14,2),
    total DECIMAL(14,2),
    due_date DATE,
    status VARCHAR(50),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create invoice items
CREATE TABLE IF NOT EXISTS invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT,
    description VARCHAR(500),
    quantity DOUBLE PRECISION,
    rate DECIMAL(14,2),
    amount DECIMAL(14,2),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create notification templates
CREATE TABLE IF NOT EXISTS notification_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(100),
    subject VARCHAR(255),
    body TEXT,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create notifications
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel VARCHAR(50),
    title VARCHAR(255),
    body TEXT,
    status VARCHAR(50),
    sent_at TIMESTAMP,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create chat messages
CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query TEXT,
    response TEXT,
    context_json TEXT,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create ai query history
CREATE TABLE IF NOT EXISTS ai_query_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediction_type VARCHAR(100),
    predicted_value VARCHAR(255),
    confidence_score DOUBLE PRECISION,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create dashboard snapshots
CREATE TABLE IF NOT EXISTS dashboard_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date DATE,
    kpis_json TEXT,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create webhooks
CREATE TABLE IF NOT EXISTS webhooks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(500),
    events VARCHAR(500),
    is_active BOOLEAN,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create api keys
CREATE TABLE IF NOT EXISTS api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_value VARCHAR(255),
    description VARCHAR(255),
    expiry_date DATE,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create financial accounts
CREATE TABLE IF NOT EXISTS financial_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name VARCHAR(255),
    balance DECIMAL(14,2),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create financial transactions
CREATE TABLE IF NOT EXISTS financial_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50),
    amount DECIMAL(14,2),
    category VARCHAR(255),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create vendors
CREATE TABLE IF NOT EXISTS vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    type VARCHAR(100),
    outstanding_balance DECIMAL(14,2),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create vendor payments
CREATE TABLE IF NOT EXISTS vendor_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id BIGINT,
    amount DECIMAL(14,2),
    payment_method VARCHAR(100),
    date DATE,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create depreciation logs
CREATE TABLE IF NOT EXISTS depreciation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT,
    amount DECIMAL(14,2),
    depreciation_date DATE,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Create workflow tasks
CREATE TABLE IF NOT EXISTS workflow_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type VARCHAR(100),
    description VARCHAR(255),
    status VARCHAR(50),
    assigned_to_role VARCHAR(50),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
